branches:
  only:
  - main

language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --compress --parallel
  - docker tag udagram-api-feed hpdtruong/udagram-api-feed:latest
  - docker tag udagram-api-user hpdtruong/udagram-api-user:latest
  - docker tag udagram-frontend hpdtruong/udagram-frontend:latest
  - docker tag reverseproxy hpdtruong/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hpdtruong/udagram-api-feed
  - docker push hpdtruong/udagram-api-user
  - docker push hpdtruong/udagram-frontend
  - docker push hpdtruong/reverseproxy
